name: TODO
description: This is what will be worked on
title: "[TODO] "
labels: [todo]
assignees:
  - ITegs
body:
  - type: textarea
    id: details
    attributes:
      label: More information
      placeholder: (optional)
    validations:
      required: false
