name: Add labeled issue to todo project
on:
  issues:
    types:
      - labeled
jobs:
  add-to-todo:
    if: github.event.label.name == 'todo'
    runs-on: ubuntu-latest
    steps:
     - uses: alex-page/github-project-automation-plus@5bcba1c1c091a222584d10913e5c060d32c44044
        with:
          project: TODO
          column: To do
          repo-token: ${{ secrets.REPO_TOKEN }}